export const BLOG_REQUEST = "BLOG_REQUEST";
export const BLOG_SUCCESS = "BLOG_SUCCESS";
export const BLOG_FAIL = "BLOG_FAIL";

export const GETALL_BLOG_REQUEST = "GETALL_BLOG_REQUEST";
export const GETALL_BLOG_SUCCESS = "GETALL_BLOG_SUCCESS";
export const GETALL_BLOG_FAIL = "GETALL_BLOG_FAIL";

export const UPDATE_BLOG_REQUEST = "UPDATE_BLOG_REQUEST";
export const UPDATE_BLOG_SUCCESS = "UPDATE_BLOG_SUCCESS";
export const UPDATE_BLOG_FAIL = "UPDATE_BLOG_FAIL";
