export const CATEGORY_REQUEST = "CATEGORY_REQUEST";
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS";
export const CATEGORY_FAIL = "CATEGORY_FAIL";

export const GETALL_CATEGORY_REQUEST = "GETALL_CATEGORY_REQUEST";
export const GETALL_CATEGORY_SUCCESS = "GETALL_CATEGORY_SUCCESS";
export const GETALL_CATEGORY_FAIL = "GETALL_CATEGORY_FAIL";